version: "3.4"

services:
  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./configs/loki/loki-local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logs
    ports:
      - "3100:3100"

  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - grafana
      - logs
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    networks:
      - grafana
      - logs
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=blackmirror1-singlestat-math-panel
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: InfluxDB
          type: influxdb
          access: proxy
          orgId: 1
          url: http://influxdb:8086
          database: k6
          user: admin
          password: admin
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - ./configs/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./configs/grafana/dashboards/:/var/lib/grafana/dashboards/

  chronograf:
    image: chronograf:1.8
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=root
      - INFLUXDB_SKIP_VERIFY=true
    depends_on:
      - influxdb
    networks:
      - k6

  k6:
    image: grafana/k6
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./src/tests:/scripts
  # k6:
  #   image: k6:Custom
  #   build: ./k6
  #   environment:
  #     - TEST=$TEST
  #     - SCENARIOS=$SCENARIOS
  #     - LOG_FILE=$LOG_FILE
  #   # command: run /dist/$TEST.js
  #   # command: run --log-output=loki=http://localhost:3100/loki/api/v1/push,label.qa=k6 /dist/$TEST.js
  #   # command: run --out influxdb=http://localhost:8086/k6 /dist/$TEST.js
  #   # command: run --out influxdb=http://localhost:8086/k6 --log-output=loki=http://localhost:3100/loki/api/v1/push,label.qa=k6 --env SCENARIOS=$SCENARIOS /dist/$TEST.js
  #   # command: run --out influxdb=http://localhost:8086/k6 --log-output=file=/logs/test-$LOG_FILE.log --env SCENARIOS=$SCENARIOS /dist/$TEST.js
  #   command: run --out influxdb=http://localhost:8086/k6 --log-output=file=/logs/test-$LOG_FILE.log --env SCENARIOS=$SCENARIOS --quiet /dist/$TEST.js
  #   volumes:
  #     # - build:/dist
  #     - logs:/logs
  #   # depends_on:
  #   #   - build
  #   # network_mode: host
  #   networks:
  #     - k6
  #     - logs
  #   ports:
  #     - "5665:5665"

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./configs/Promtail/promtail-local-config.yaml:/etc/promtail/local-config.yaml
      - logs:/logs
    command: -config.file=/etc/promtail/local-config.yaml
    # networks:
    #   - logs
    #   - k6
    network_mode: host
networks:
  k6:
  grafana:
  logs:
volumes:
  influxdb-data:
  loki-data:
  logs:
