apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  database: k6
  user: croco
  password: password1
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  secureJsonData:
    token: token1
  jsonData:
    version: Flux
    organization: k6io
    defaultBucket: demo
